# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 545)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Search = QtWidgets.QLineEdit(self.centralwidget)
        self.Search.setObjectName("Search")
        self.verticalLayout.addWidget(self.Search)
        self.Searchbutton = QtWidgets.QToolButton(self.centralwidget)
        self.Searchbutton.setObjectName("Searchbutton")
        self.verticalLayout.addWidget(self.Searchbutton)
        self.Packets = QtWidgets.QTableWidget(self.centralwidget)
        self.Packets.setObjectName("Packets")
        self.Packets.setColumnCount(7)
        self.Packets.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.Packets)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.pack_info = QtWidgets.QTreeWidget(self.centralwidget)
        self.pack_info.setObjectName("pack_info")
        item_0 = QtWidgets.QTreeWidgetItem(self.pack_info)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.pack_info)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.pack_info)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.pack_info)
        item_0 = QtWidgets.QTreeWidgetItem(self.pack_info)
        self.verticalLayout.addWidget(self.pack_info)
        self.pack_hex = QtWidgets.QTextBrowser(self.centralwidget)
        self.pack_hex.setObjectName("pack_hex")
        self.verticalLayout.addWidget(self.pack_hex)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCapture = QtWidgets.QMenu(self.menubar)
        self.menuCapture.setObjectName("menuCapture")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionRestart = QtWidgets.QAction(MainWindow)
        self.actionRestart.setObjectName("actionRestart")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuCapture.addAction(self.actionStart)
        self.menuCapture.addAction(self.actionStop)
        self.menuCapture.addAction(self.actionRestart)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCapture.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Search.setText(_translate("MainWindow", "Filter"))
        self.Searchbutton.setText(_translate("MainWindow", "Search"))
        item = self.Packets.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No"))
        item = self.Packets.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.Packets.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Source"))
        item = self.Packets.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Destination"))
        item = self.Packets.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Protocol"))
        item = self.Packets.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Length"))
        item = self.Packets.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Info"))
        __sortingEnabled = self.pack_info.isSortingEnabled()
        self.pack_info.setSortingEnabled(False)
        self.pack_info.topLevelItem(0).setText(0, _translate("MainWindow", "IP"))
        self.pack_info.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.pack_info.topLevelItem(1).setText(0, _translate("MainWindow", "HTTP"))
        self.pack_info.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.pack_info.topLevelItem(2).setText(0, _translate("MainWindow", "Transmission control protocol"))
        self.pack_info.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.pack_info.topLevelItem(3).setText(0, _translate("MainWindow", "New Item"))
        self.pack_info.topLevelItem(4).setText(0, _translate("MainWindow", "New Item"))
        self.pack_info.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCapture.setTitle(_translate("MainWindow", "Capture"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionRestart.setText(_translate("MainWindow", "Restart"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

